public class CallDoctorPatientWrapper {

    public String staff_id;
    public String patient_name;
    public String patient_phone;
    public String doctor_name;
    public String doctor_phone;
    public String clientname;
    public String token;
    
    public CallDoctorPatientWrapper(){
        
        staff_id ='';
        patient_name ='';
        patient_phone ='';
        doctor_name='';
        doctor_phone='';
        clientname='max';
        token='5fd53b477b6a275185307208f985b340';
        
    }
    
    
}