@istest
public class ClevertapTest {
        public static testmethod void myUnitTest(){
        Clevertap.AddAppointmentLeadWrapper a = new Clevertap.AddAppointmentLeadWrapper();
            a.Name='hello';       
            a.Email='hello';
            a.DoctorLead='hello';  
            a.Mobile_Phone='hello';
            a.hospitallead='hello';
            a.MaxID='hello';
            a.PatientName='hello';
            a.patientGender='hello';
            a.Speciality='hello';
            a.Status='hello';
            a.Age=22;
            a.AppointmentDateTime=System.today();
            a.LastModified=System.today();
            a.DOBlead= System.today();
}
}