public class GeneratePaymentLinkWrapper {
    
    public GeneratePaymentLinkWrapper(){
        LeadId = '';
        TransactionId = '';
        FirstName = '';
        LastName = '';
        Amount = 0.0;
        EmailId = '';
        MobileNumber = '';
        ServiceId = '';
        Age = 0;
        Gender = '';
        CityId = '';
        StateId = '';
        LocationId = '';
        DOB = null;
        Userid = '';
        MaxId = '';
        PatientId = '';
        DeliveryAddress = '';
        ServiceItemID = '';
        DiscountID = '';
        DiscountAmount = '';
        OrderQty = '';
        RefDoctorID = '';
        CompanyID = '';
        PackageID = '';
        IsDiscountApplicable = '';
        IsAdvance = '';
        IsServiceApplicable = '';
        SessionId = '';
        MacAddress = '';
    }
    
    
    public String LeadId;
    public String TransactionId;
    public String FirstName;
    public String LastName;
    public Decimal Amount;
    public String EmailId;
    public String MobileNumber;
    public String ServiceId;
    public Decimal Age;
    public String Gender;
    public String CityId;
    public String StateId;
    public String LocationId;
    public Date DOB;
    public String Userid;
    public String MaxId;
    public String PatientId;
    public String DeliveryAddress;
    public String ServiceItemID;
    public String DiscountID;
    public String DiscountAmount;
    public String OrderQty;
    public String RefDoctorID;
    public String CompanyID;
    public String PackageID;
    public String IsDiscountApplicable;
    public String IsAdvance;
    public String IsServiceApplicable;
    public String SessionId;
    public String MacAddress;
    
}